runs:
  using: "composite"
  steps:
    #NOTE: This action is just a normal commit action
    - uses: EndBug/add-and-commit@v9
      if: ${{ !inputs.app_id }}
      with:
        cwd: homebrew-tap
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: ${{ steps.summary.outputs.message }}
        github_token: ${{ inputs.token }}
        default_author: github_actions
        fetch: false

      #NOTE: This action does not support app_id and app_private_key
    - name: Commit changes
      uses: iarekylew00t/verified-bot-commit@v2
      with:
        files: Formula/*
        token: ${{ inputs.token }}
        workspace: homebrew-tap
        ref: refs/heads/${{ steps.branch.outputs.default }}
        repository: ${{ inputs.repo }}
        message: ${{ steps.summary.outputs.message }}

    #NOTE: This is the original method, true and tested, but lame
    - name: "Commit and Push"
      working-directory: homebrew-tap
      shell: bash
      run: |
        echo "message: ${{ steps.summary.outputs.message }}"
        echo "name: github-actions[bot]"
        echo "email: 41898282+github-actions[bot]@users.noreply.github.com"

        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "${{ steps.summary.outputs.message }}"
        git remote set-url origin "https://${{ inputs.token }}@github.com/${{ inputs.repo }}"
        git push -u origin ${{ steps.branch.outputs.default }}
