name: "Homebrew"

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: "Homebrew"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      repo: "cssnr/tap"
      path: "homebrew"
      branch: "master"
      formula: "toml-run.rb"

    steps:
      - name: "Checkout Homebrew"
        uses: actions/checkout@v6
        with:
          repository: ${{ env.repo }}
          ref: ${{ env.branch }}
          path: ${{ env.path }}
          persist-credentials: false

      - name: "Update Formula"
        shell: bash
        run: |
          line=$(grep -n -m1 version "${{ env.path }}/Formula/${{ env.formula }}" | cut -f1 -d:)
          sed -i "${line}"'s/.*/  version "${{ github.ref_name }}"/' "${{ env.path }}/Formula/${{ env.formula }}"
          cat "${{ env.path }}/Formula/${{ env.formula }}"

      - name: "Commit and Push"
        working-directory: ${{ env.path }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Bump ${{ env.formula }} to ${{ github.ref_name }}"
          git remote set-url origin "https://${{ secrets.HOMEBREW_PAT }}@github.com/${{ env.repo }}"
          git push -u origin ${{ env.branch }}

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@b8381b25576cb341b2af39926ab42c5056cc44ed # v1.15.5
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
