name: "Homebrew Action"
description: "Homebrew Action to Update Formula."
author: "Shane"

branding:
  icon: git-pull-request
  color: "orange"

inputs:
  url:
    description: "URL to update."
    default: ""
  sha256:
    description: "SHA256 hash to update."
    default: ""
  version:
    description: "Version to update."
    default: ""
  repo:
    description: "Homebrew Tap: owner/name"
    required: true
  formula:
    description: "Formula file name."
    default: ""
  message:
    description: "Commit message."
    default: ""
  branch:
    description: "Branch to Checkout and Commit."
    default: ""
  token:
    description: "Fine Grained or PAT w/ contents: write"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Debug Inputs"
      shell: bash
      run: |
        echo "inputs.url: ${{ inputs.url }}"
        echo "inputs.sha256: ${{ inputs.sha256 }}"
        echo "inputs.version: ${{ inputs.version }}"

        echo "inputs.repo: ${{ inputs.repo }}"
        echo "inputs.formula: ${{ inputs.formula }}"
        echo "inputs.message: ${{ inputs.message }}"
        echo "inputs.branch: ${{ inputs.branch }}"

    - name: "Get Default Branch"
      id: branch
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [ -n "${{ inputs.branch }}" ];then
          branch="${{ inputs.branch }}"
        else
          branch="$(gh repo view ${{ inputs.repo }} --json defaultBranchRef --jq .defaultBranchRef.name)"
        fi
        echo "branch: ${branch}"
        echo "default=${branch}" >> "$GITHUB_OUTPUT"

    - name: "Checkout Homebrew Tap"
      uses: actions/checkout@v6
      with:
        path: homebrew-tap
        persist-credentials: false
        ref: ${{ steps.branch.outputs.default }}
        repository: ${{ inputs.repo }}

    - name: "Set Formula File"
      env:
        path: homebrew-tap/Formula
      shell: bash
      run: |
        echo "::group::ls ${{ env.path }}"
        ls -lah "${{ env.path }}"
        echo "::endgroup::"

        if [ -n "${{ inputs.formula }}" ];then
          if [ -f "${{ env.path }}/${{ inputs.formula }}" ];then
            echo "formula=${{ env.path }}/${{ inputs.formula }}" >> "$GITHUB_ENV"
          elif [ -f "${{ env.path }}/${{ inputs.formula }}.rb" ];then
            echo "formula=${{ env.path }}/${{ inputs.formula }}.rb" >> "$GITHUB_ENV"
          fi
        else
          echo "formula=${{ env.path }}/${GITHUB_REPOSITORY#*/}.rb" >> "$GITHUB_ENV"
        fi

    - name: "Update Formula"
      shell: bash
      run: |
        echo "formula: ${{ env.formula }}"
        if [ ! -f "${{ env.formula }}" ];then
          echo "::error::Not a File: ${{ env.formula }}"
          exit 1
        fi

        bash "${{ github.action_path }}/src/update-formula.sh" url "${{ inputs.url }}"
        bash "${{ github.action_path }}/src/update-formula.sh" sha256 "${{ inputs.sha256 }}"
        bash "${{ github.action_path }}/src/update-formula.sh" version "${{ inputs.version }}"

        echo "::group::cat ${{ env.formula }}"
        cat -n "${{ env.formula }}"
        echo "::endgroup::"

    - name: "Job Summary"
      id: summary
      working-directory: homebrew-tap
      shell: bash
      run: |
        file="$(basename ${{ env.formula }})"
        echo "file: ${file}"

        if [ -n "${{ inputs.message }}" ];then
          message="${{ inputs.message }}" >> "$GITHUB_OUTPUT"
        elif [ -n "${{ inputs.version }}" ];then
          message="Bump ${file} to ${{ inputs.version }}" >> "$GITHUB_OUTPUT"
        else
          message="Bump ${file}" >> "$GITHUB_OUTPUT"
        fi

        echo "message: ${message}"
        echo "message=${message}" >> "$GITHUB_OUTPUT"

        diff="$(git diff -U0 Formula)"
        echo "::group::diff"
        echo "${diff}"
        echo "::endgroup::"

        md="Formula: \`Formula/${file}\`\n"
        md+="URL: \`${{ inputs.url || 'not updated' }}\`\n"
        md+="SHA256: \`${{ inputs.sha256 || 'not updated' }}\`\n"
        md+="Version: \`${{ inputs.version || 'not updated' }}\`\n"
        md+="git diff:\n\`\`\`text\n${diff}\n\`\`\`\n"
        echo -e "${md}" >> "$GITHUB_STEP_SUMMARY"

    - name: "Commit and Push"
      working-directory: homebrew-tap
      shell: bash
      run: |
        echo "message: ${{ steps.summary.outputs.message }}"
        echo "name: github-actions[bot]"
        echo "email: 41898282+github-actions[bot]@users.noreply.github.com"

        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "${{ steps.summary.outputs.message }}"
        git remote set-url origin "https://${{ inputs.token }}@github.com/${{ inputs.repo }}"
        git push -u origin ${{ steps.branch.outputs.default }}
