name: "Homebrew Action"
description: "Homebrew Action to Update Custom Tap Formula url, sha256 and version with Verified Commits."
author: "Shane"

branding:
  icon: git-pull-request
  color: "orange"

inputs:
  url:
    description: "Formula URL to update."
    default: ""
  sha256:
    description: "Formula Hash to update."
    default: ""
  version:
    description: "Formula Version to update."
    default: ""
  calculate:
    description: "Calculate sha256 from url."
    default: "true"
  repo:
    description: "Homebrew Tap: owner/name"
    required: true
  formula:
    description: "Formula file name."
    default: ""
  message:
    description: "Commit message."
    default: ""
  branch:
    description: "Branch to Checkout."
    default: ""
  head_branch:
    description: "Branch to Push Too."
    default: ""
  create_branch:
    description: "Create Head Branch."
    default: "false"
  token:
    description: "Fine Grained or PAT w/ contents: write"
    default: ${{ github.token }}
  app_id:
    description: "App ID"
    default: ""
  app_private_key:
    description: "App Private Key"
    default: ""
  commit:
    description: "Commit and Push Changes"
    default: "true"
  pull:
    description: "Create Pull Request"
    default: "false"

outputs:
  formula:
    description: "Formula File"
    value: ${{ steps.summary.outputs.formula }}
  message:
    description: "Commit Message"
    value: ${{ steps.summary.outputs.message }}
  branch:
    description: "Branch Used"
    value: ${{ steps.summary.outputs.branch }}
  sha256:
    description: "Formula Hash"
    value: ${{ steps.summary.outputs.sha256 }}
  sha:
    description: "Commit Hash"
    value: ${{ steps.commit.outputs.sha }}

runs:
  using: "composite"
  steps:
    - name: "Inputs"
      id: inputs
      shell: bash
      run: |
        echo "inputs.url: ${{ inputs.url }}"
        echo "inputs.sha256: ${{ inputs.sha256 }}"
        echo "inputs.version: ${{ inputs.version }}"
        echo "inputs.calculate: ${{ inputs.calculate }}"

        echo "inputs.repo: ${{ inputs.repo }}"
        echo "inputs.formula: ${{ inputs.formula }}"
        echo "inputs.message: ${{ inputs.message }}"
        echo "inputs.branch: ${{ inputs.branch }}"
        echo "inputs.head_branch: ${{ inputs.head_branch }}"

        echo "inputs.app_id: ${{ inputs.app_id }}"
        echo "inputs.commit: ${{ inputs.commit }}"
        echo "inputs.pull: ${{ inputs.pull }}"

        owner="$(echo "${{ inputs.repo }}" | cut -d "/" -f 1)"
        echo "owner: ${owner}"
        echo "owner=${owner}" >> "$GITHUB_OUTPUT"
        repo="$(echo "${{ inputs.repo }}" | cut -d "/" -f 2)"
        echo "repo: ${repo}"
        echo "repo=${repo}" >> "$GITHUB_OUTPUT"

    - name: "Create App Token"
      if: ${{ inputs.app_id }}
      uses: actions/create-github-app-token@v2
      id: token
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}
        owner: ${{ steps.inputs.outputs.owner }}
        repositories: ${{ steps.inputs.outputs.repo }}

    # TODO: Determine if App or Token, set output, and use in workflow...
    - name: "Get User"
      id: user
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
      shell: bash
      run: |
        name="${{ steps.token.outputs.app-slug }}[bot]"
        echo "name: ${name}"
        echo "name=${name}" >> "$GITHUB_OUTPUT"

        url="/users/${name}"
        echo "url: ${url}"
        user_id="$(gh api "${url}" --jq .id)"
        echo "user_id: ${user_id}"

        email="${user_id}+${name}@users.noreply.github.com"
        echo "email: ${email}"
        echo "email=${email}" >> "$GITHUB_OUTPUT"

        string="${name} <${email}>"
        echo "string: ${string}"
        echo "string=${string}" >> "$GITHUB_OUTPUT"

    - name: "Get Default Branch"
      id: branch
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
      shell: bash
      run: |
        if [ -n "${{ inputs.branch }}" ];then
          branch="${{ inputs.branch }}"
        else
          branch="$(gh repo view ${{ inputs.repo }} --json defaultBranchRef --jq .defaultBranchRef.name)"
        fi

        echo "branch: ${branch}"
        if [ -z "${branch}" ];then
          echo "::error::Unable to determine default branch."
          exit 1
        fi
        echo "branch=${branch}" >> "$GITHUB_ENV"

        if [ -n "${{ inputs.head_branch }}" ];then
          head_branch="${{ inputs.head_branch }}"
        elif [ "${{ inputs.pull }}" != "false" ];then
          head_branch="bump-formula-${{ github.run_number }}"
        elif [ "${{ inputs.create_branch }}" != "false" ];then
          head_branch="bump-formula-${{ github.run_number }}"
        else
          head_branch="${branch}"
        fi
        echo "head_branch: ${head_branch}"
        echo "head_branch=${head_branch}" >> "$GITHUB_ENV"

    - name: "Checkout Homebrew Tap"
      uses: actions/checkout@v6
      with:
        path: homebrew-tap
        persist-credentials: false
        ref: ${{ env.branch }}
        repository: ${{ inputs.repo }}
        token: ${{ steps.token.outputs.token }}

    - name: "Set Formula File"
      env:
        path: homebrew-tap/Formula
      shell: bash
      run: |
        echo "::group::ls ${{ env.path }}"
        ls -lah "${{ env.path }}"
        echo "::endgroup::"

        if [ -n "${{ inputs.formula }}" ];then
          name="${{ inputs.formula }}"
        else
          name="${GITHUB_REPOSITORY#*/}"
        fi
        echo "name: ${name}"
        letter="$(echo "${name}" | head -c1)"
        echo "letter: ${letter}"

        if [ -f "${{ env.path }}/${name}" ];then
          formula="${{ env.path }}/${name}"
        elif [ -f "${{ env.path }}/${name}.rb" ];then
          formula="${{ env.path }}/${name}.rb"
        elif [ -f "${{ env.path }}/${letter}/${name}" ];then
          formula="${{ env.path }}/${letter}/${name}"
        elif [ -f "${{ env.path }}/${letter}/${name}.rb" ];then
          formula="${{ env.path }}/${letter}/${name}.rb"
        else
          echo "::error::Formula Not Found: ${name}"
          exit 1
        fi
        echo "formula: ${formula}"
        echo "formula=${formula}" >> "$GITHUB_ENV"

    - name: "Calculate Hash"
      shell: bash
      run: |
        unset sha256
        if [ -n "${{ inputs.sha256 }}" ];then
          sha256="$(echo "${{ inputs.sha256 }}" | cut -d ':' -f 2)"
        elif [ "${{ inputs.calculate }}" == "true" ];then
          if [ -n "${{ inputs.url }}" ];then
            echo "Downloading url: ${{ inputs.url }}"
            wget -O "${{ runner.temp }}/download" "${{ inputs.url }}"
            stat "${{ runner.temp }}/download"
            sha256sum "${{ runner.temp }}/download"
            sha256="$(sha256sum "${{ runner.temp }}/download" | awk '{print $1}')"
          else
            echo "::warning::To calculate the sha256 you must provide the url."
          fi
        fi
        echo "sha256: ${sha256}"
        echo "sha256=${sha256}" >> "$GITHUB_ENV"

    - name: "Update Formula"
      shell: bash
      run: |
        echo "formula: ${{ env.formula }}"

        bash "${{ github.action_path }}/src/update-formula.sh" url "${{ inputs.url }}"
        bash "${{ github.action_path }}/src/update-formula.sh" sha256 "${{ env.sha256 }}"
        bash "${{ github.action_path }}/src/update-formula.sh" version "${{ inputs.version }}"

        echo "::group::cat ${{ env.formula }}"
        cat -n "${{ env.formula }}"
        echo "::endgroup::"

    - name: "Job Summary"
      id: summary
      working-directory: homebrew-tap
      shell: bash
      run: |
        echo "sha256=${{ env.sha256 }}" >> "$GITHUB_OUTPUT"
        echo "branch=${{ env.head_branch }}" >> "$GITHUB_OUTPUT"

        file="$(basename ${{ env.formula }})"
        echo "formula=${file}" >> "$GITHUB_OUTPUT"

        if [ -n "${{ inputs.message }}" ];then
          message="${{ inputs.message }}"
        elif [ -n "${{ inputs.version }}" ];then
          message="Bump ${file} to ${{ inputs.version }}"
        else
          message="Bump ${file}"
        fi
        echo "message: ${message}"
        echo "message=${message}" >> "$GITHUB_OUTPUT"

        diff="$(git diff -U0 Formula)"
        echo "::group::git diff"
        echo "${diff}"
        echo "::endgroup::"

        file_url="https://github.com/${{ inputs.repo }}/blob/${{ env.head_branch }}/Formula/${file}"
        echo "file_url: ${file_url}"

        md="message: **${message}**\n"
        md+="formula: [Formula/${file}](${file_url})\n"
        md+="url: \`${{ inputs.url || 'not provided' }}\`\n"
        md+="sha256: \`${{ env.sha256 || 'not provided' }}\`\n"
        md+="version: \`${{ inputs.version || 'not provided' }}\`\n"
        md+="git diff:\n\`\`\`text\n${diff}\n\`\`\`\n"
        echo -e "${md}" >> "$GITHUB_STEP_SUMMARY"

    - name: "Commit Action"
      if: ${{ inputs.commit == 'true' }}
      id: commit
      uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
      with:
        root_dir: homebrew-tap
        branch: ${{ env.head_branch }}
        repository: ${{ inputs.repo }}
        commit_message: ${{ steps.summary.outputs.message }}
        #github_token: ${{ inputs.app_id == '' && inputs.token || '' }}
        #app_id: ${{ inputs.app_id }}
        #app_private_key: ${{ inputs.app_private_key }}
        github_token: ${{ steps.token.outputs.token }}

    - name: "Create Pull Request"
      if: ${{ inputs.pull == 'true' }}
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ steps.token.outputs.token }}
        path: homebrew-tap
        title: ${{ steps.summary.outputs.message }}
        commit-message: ${{ steps.summary.outputs.message }}
        branch: ${{ env.head_branch }}
        base: ${{ env.branch }}
        committer: ${{ steps.user.outputs.string }}
        body: "Disable Advertising"
