name: "Homebrew Action"
description: "Homebrew Action to Update Custom Tap Formula url, sha256 and version with Verified Commits."
author: "Shane"

branding:
  icon: git-pull-request
  color: "orange"

inputs:
  url:
    description: "Formula URL to update."
    default: ""
  sha256:
    description: "Formula Hash to update."
    default: ""
  version:
    description: "Formula Version to update."
    default: ""
  calculate:
    description: "Calculate sha256 from url."
    default: "true"
  file:
    description: "Full Formula File (overrides other inputs)."
    default: ""
  repo:
    description: "Homebrew Tap: owner/name"
    required: true
  formula:
    description: "Formula file name."
    default: ""
  message:
    description: "Commit message."
    default: ""
  branch:
    description: "Branch to Checkout."
    default: ""
  head_branch:
    description: "Branch to Push Too."
    default: ""
  create_branch:
    description: "Create Head Branch."
    default: "false"
  token:
    description: "Fine Grained or PAT w/ contents: write"
    default: ${{ github.token }}
  app_id:
    description: "App ID"
    default: ""
  app_private_key:
    description: "App Private Key"
    default: ""
  commit:
    description: "Commit and Push Changes"
    default: "true"
  pull:
    description: "Create Pull Request"
    default: "false"

outputs:
  formula:
    description: "Formula File"
    value: ${{ steps.summary.outputs.formula }}
  message:
    description: "Commit Message"
    value: ${{ steps.summary.outputs.message }}
  branch:
    description: "Branch Used"
    value: ${{ steps.summary.outputs.branch }}
  sha256:
    description: "Formula Hash"
    value: ${{ steps.summary.outputs.sha256 }}
  sha:
    description: "Commit Hash"
    value: ${{ steps.commit.outputs.sha }}
  pull:
    description: "Pull Request JSON"
    value: ${{ steps.pull.outputs.pull }}

runs:
  using: "composite"
  steps:
    - name: "Inputs"
      id: inputs
      shell: bash
      run: |
        echo "::group::Inputs"

        echo "inputs.url: ${{ inputs.url }}"
        echo "inputs.sha256: ${{ inputs.sha256 }}"
        echo "inputs.version: ${{ inputs.version }}"
        echo "inputs.calculate: ${{ inputs.calculate }}"
        echo "inputs.file: ${{ inputs.file }}"

        echo "inputs.repo: ${{ inputs.repo }}"
        echo "inputs.formula: ${{ inputs.formula }}"
        echo "inputs.message: ${{ inputs.message }}"
        echo "inputs.branch: ${{ inputs.branch }}"
        echo "inputs.head_branch: ${{ inputs.head_branch }}"

        echo "inputs.app_id: ${{ inputs.app_id }}"
        echo "inputs.commit: ${{ inputs.commit }}"
        echo "inputs.pull: ${{ inputs.pull }}"

        echo "::endgroup::"

        owner="$(echo "${{ inputs.repo }}" | cut -d "/" -f 1)"
        echo "1ï¸âƒ£ owner: ${owner}"
        echo "owner=${owner}" >> "$GITHUB_OUTPUT"
        repo="$(echo "${{ inputs.repo }}" | cut -d "/" -f 2)"
        echo "2ï¸âƒ£ repo: ${repo}"
        echo "repo=${repo}" >> "$GITHUB_OUTPUT"

        if [ -n "${{ inputs.file }}" ];then
          if [ ! -f "${{ inputs.file }}" ];then
            echo "::error::Input file provided but not found: ${{ inputs.file }}"
            exit 1
          fi
          [ -n "${{ inputs.url }}" ] && echo "::warning::Input url ignored when providing a file."
          [ -n "${{ inputs.sha256 }}" ] && echo "::warning::Input sha256 ignored when providing a file."
          [ -n "${{ inputs.version }}" ] && echo "::warning::Input version ignored when providing a file."
        fi

    - name: "Create App Token"
      if: ${{ inputs.app_id }}
      uses: actions/create-github-app-token@v2
      id: app
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}
        owner: ${{ steps.inputs.outputs.owner }}
        repositories: ${{ steps.inputs.outputs.repo }}

    - name: "Set Token"
      id: token
      shell: bash
      run: |
        if [ -n "${{ inputs.app_id }}" ];then
          echo "ðŸ¤– Using Generated App Token"
          token="${{ steps.app.outputs.token }}"
        else
          echo "ðŸ§‘ Using User Provided Token"
          token="${{ inputs.token }}"
        fi
        if [ -z "${token}" ];then
          echo "::error::Error processing access token."
          exit 1
        fi
        echo "token=${token}" >> "$GITHUB_OUTPUT"

    - name: "Set Branch"
      id: branch
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
      shell: bash
      run: |
        if [ -n "${{ inputs.branch }}" ];then
          branch="${{ inputs.branch }}"
        else
          branch="$(gh repo view ${{ inputs.repo }} --json defaultBranchRef --jq .defaultBranchRef.name)"
        fi
        echo "â–¶ï¸ branch: ${branch}"
        if [ -z "${branch}" ];then
          echo "::error::Unable to determine default branch."
          exit 1
        fi
        echo "branch=${branch}" >> "$GITHUB_ENV"

        if [ -n "${{ inputs.head_branch }}" ];then
          head_branch="${{ inputs.head_branch }}"
        elif [ "${{ inputs.pull }}" != "false" ];then
          head_branch="bump-formula-${{ github.run_number }}"
        elif [ "${{ inputs.create_branch }}" != "false" ];then
          head_branch="bump-formula-${{ github.run_number }}"
        else
          head_branch="${branch}"
        fi
        echo "ðŸ”„ head_branch: ${head_branch}"
        echo "head_branch=${head_branch}" >> "$GITHUB_ENV"

    - name: "Checkout Homebrew Tap"
      uses: actions/checkout@v6
      with:
        path: homebrew-tap
        persist-credentials: false
        show-progress: false
        ref: ${{ env.branch }}
        repository: ${{ inputs.repo }}
        token: ${{ steps.token.outputs.token }}

    - name: "Set Formula"
      env:
        path: homebrew-tap/Formula
      shell: bash
      run: |
        echo "Formula Path: ${{ env.path }}"
        echo "::group::ls ${{ env.path }}"
        ls -lah "${{ env.path }}"
        echo "::endgroup::"

        if [ -n "${{ inputs.formula }}" ];then
          name="${{ inputs.formula }}"
        else
          name="${GITHUB_REPOSITORY#*/}"
        fi
        echo "name: ${name}"
        letter="$(echo "${name}" | head -c1)"
        echo "letter: ${letter}"

        if [ -f "${{ env.path }}/${name}" ];then
          formula="${{ env.path }}/${name}"
        elif [ -f "${{ env.path }}/${name}.rb" ];then
          formula="${{ env.path }}/${name}.rb"
        elif [ -f "${{ env.path }}/${letter}/${name}" ];then
          formula="${{ env.path }}/${letter}/${name}"
        elif [ -f "${{ env.path }}/${letter}/${name}.rb" ];then
          formula="${{ env.path }}/${letter}/${name}.rb"
        else
          echo "::error::Formula Not Found: ${name}"
          exit 1
        fi
        echo "ðŸ“’ formula: ${formula}"
        echo "formula=${formula}" >> "$GITHUB_ENV"

    - name: "Set Hash"
      if: ${{ !inputs.file }}
      shell: bash
      run: |
        unset sha256
        if [ -n "${{ inputs.sha256 }}" ];then
          sha256="$(echo "${{ inputs.sha256 }}" | cut -d ':' -f 2)"
        elif [ "${{ inputs.calculate }}" == "true" ];then
          if [ -n "${{ inputs.url }}" ];then
            echo "ðŸŒ Downloading url: ${{ inputs.url }}"
            wget -O "${{ runner.temp }}/download" "${{ inputs.url }}"
            stat "${{ runner.temp }}/download"
            sha256sum "${{ runner.temp }}/download"
            sha256="$(sha256sum "${{ runner.temp }}/download" | awk '{print $1}')"
          else
            echo "::warning::To calculate the sha256 you must provide the url."
          fi
        fi
        echo "#ï¸âƒ£ sha256: ${sha256}"
        echo "sha256=${sha256}" >> "$GITHUB_ENV"

    - name: "Update Formula"
      if: ${{ !inputs.file }}
      shell: bash
      run: |
        echo "formula: ${{ env.formula }}"

        bash "${{ github.action_path }}/src/update-formula.sh" url "${{ inputs.url }}"
        bash "${{ github.action_path }}/src/update-formula.sh" sha256 "${{ env.sha256 }}"
        bash "${{ github.action_path }}/src/update-formula.sh" version "${{ inputs.version }}"

        echo "::group::cat ${{ env.formula }}"
        cat -n "${{ env.formula }}"
        echo "::endgroup::"

    - name: "Update Formula File"
      if: ${{ inputs.file }}
      shell: bash
      run: |
        echo "file: ${{ inputs.file }}"
        echo "::group::cat ${{ inputs.file }}"
        cat -n "${{ inputs.file }}"
        echo "::endgroup::"
        cp -f "${{ inputs.file }}" ${{ env.formula }}

    - name: "Job Summary"
      id: summary
      working-directory: homebrew-tap
      shell: bash
      run: |
        echo "sha256=${{ env.sha256 }}" >> "$GITHUB_OUTPUT"
        echo "branch=${{ env.head_branch }}" >> "$GITHUB_OUTPUT"

        file="$(basename ${{ env.formula }})"
        echo "formula=${file}" >> "$GITHUB_OUTPUT"

        if [ -n "${{ inputs.message }}" ];then
          message="${{ inputs.message }}"
        elif [ -n "${{ inputs.version }}" ];then
          message="Bump ${file} to ${{ inputs.version }}"
        else
          message="Bump ${file}"
        fi
        echo "message: ${message}"
        echo "message=${message}" >> "$GITHUB_OUTPUT"

        diff="$(git diff -U0 Formula)"
        echo "::group::git diff"
        echo "${diff}"
        echo "::endgroup::"

        file_url="https://github.com/${{ inputs.repo }}/blob/${{ env.head_branch }}/Formula/${file}"
        echo "file_url: ${file_url}"

        # TODO: Generate body for pull request...

        md="message: **${message}**\n"
        md+="formula: [Formula/${file}](${file_url})\n"
        md+="url: \`${{ inputs.url || 'not provided' }}\`\n"
        md+="sha256: \`${{ env.sha256 || 'not provided' }}\`\n"
        md+="version: \`${{ inputs.version || 'not provided' }}\`\n"
        md+="git diff:\n\`\`\`diff\n${diff}\n\`\`\`\n"
        echo -e "${md}" >> "$GITHUB_STEP_SUMMARY"

    - name: "Commit Action"
      if: ${{ inputs.commit == 'true' }}
      id: commit
      uses: suzuki-shunsuke/commit-action@f28421acc277a6d6a9c1f94ea449076ad77dba67 # v0.1.0
      with:
        root_dir: homebrew-tap
        branch: ${{ env.head_branch }}
        repository: ${{ inputs.repo }}
        commit_message: ${{ steps.summary.outputs.message }}
        github_token: ${{ steps.token.outputs.token }}
        #github_token: ${{ inputs.app_id == '' && inputs.token || '' }}
        #app_id: ${{ inputs.app_id }}
        #app_private_key: ${{ inputs.app_private_key }}

    - name: "Create Pull"
      id: pull
      if: ${{ inputs.commit == 'true' && inputs.pull != 'false' }}
      uses: cssnr/create-pull-action@v1
      with:
        repository: ${{ inputs.repo }}
        head: ${{ env.head_branch }}
        base: ${{ env.branch }}
        title: ${{ steps.summary.outputs.message }}
        body: ${{ steps.summary.outputs.message }}
        token: ${{ steps.token.outputs.token }}
        #summary: ${{ inputs.summary }}

    - name: "Debug Pull Request"
      if: ${{ inputs.commit == 'true' && inputs.pull != 'false' }}
      shell: bash
      run: |
        echo "html_url: ${{ fromJSON(steps.pull.outputs.pull).html_url }}"
        echo "number: ${{ fromJSON(steps.pull.outputs.pull).number }}"
